# Generated by Django 2.1.5 on 2019-02-07 23:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180219_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('code', wagtail.core.blocks.TextBlock(icon='code', template='blog/blocks/code.html')), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
