# Generated by Django 2.1.5 on 2019-02-08 00:35

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190207_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=blog.models.DefaultDateField(verbose_name='Post date'),
        ),
    ]
