# Generated by Django 2.2.4 on 2019-09-01 12:11

from django.db import migrations, models
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Dev Diary Entry',
                'verbose_name_plural': 'Dev Diary Entries',
            },
        ),
    ]
