# Generated by Django 2.2.4 on 2019-10-13 23:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_diaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
