# Generated by Django 2.2.4 on 2019-10-16 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0008_blogpage_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='listing_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
