# Generated by Django 2.1.7 on 2019-03-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicroBlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=420)),
                ('uri', models.URLField(blank=True)),
                ('uri_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Micro Blog Post',
                'verbose_name_plural': 'Micro Blog Posts',
            },
        ),
    ]
